# Generated by Django 3.0.1 on 2019-12-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_text', models.CharField(max_length=20)),
                ('email_text', models.EmailField(max_length=254)),
                ('password_text', models.CharField(max_length=20)),
            ],
        ),
    ]
