# Generated by Django 3.0.1 on 2020-01-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes_site', '0002_auto_20200101_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/'),
        ),
    ]
