# Generated by Django 3.0.1 on 2020-02-13 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes_site', '0007_commentvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
    ]
